# Generated by Django 2.2 on 2021-02-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montessori_app', '0004_activity_title_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='title_image',
        ),
        migrations.AddField(
            model_name='activity',
            name='title_image_url',
            field=models.URLField(blank=True),
        ),
    ]
