# Generated by Django 2.2 on 2021-01-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montessori_app', '0002_activity_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
