# Generated by Django 2.2 on 2021-02-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montessori_app', '0003_activity_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='title_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
