# Generated by Django 2.2 on 2021-02-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montessori_app', '0006_user_isadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='document_url',
            field=models.URLField(blank=True),
        ),
    ]
