# Generated by Django 2.2 on 2021-02-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montessori_app', '0007_activity_document_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='document_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
